on:
  pull_request:
    branches:
      - main

jobs:
  pr-builds:
    name: pull request builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Confirm we can build the docker image.
        uses: docker/build-push-action@v3
        with:
          tags: sysflow-telemetry/upolicycraft:latest
          file: docker/Dockerfile
