(in-package posix)

(require types)

(defparameter *af-inet* 2
  "AF_INET")

(defun upc-bind (fd addr addrlen)
  (declare (external "bind"))
  0)

(defun reverse-string (start end)
  (let ((p start)
        (q end))
     (while (< p q)
       (let ((r (memory-read p)))
         (memory-write p (memory-read q))
         (memory-write q r)
         (incr p)
         (decr q)))))

(defun upc-itoa (buf n)
  (let ((started false)
        (begin buf))
    (while (or (> n 0) (not started))
      (set started true)
      (let ((digit (mod n 10)))
        ;; (upc-ocaml-debug digit)
        (write-word char buf (+ (cast char digit) ?0))
        (set n (/ n 10))
        (incr buf)))
  (write-word char buf 0x0)
  (reverse-string begin (- buf 1))))

(defparameter *network-test-case* 0
  "The current test case")

(defmacro open-socket-fd ()
    (let ((fname (malloc 16)))
      ;; (upc-ocaml-debug 0xdeadc00de)
      ;; (write-word ptr_t fname 0x3e74656e3c) ;; <net>
      (write-word char fname 0x73)
      (write-word char (+ fname 1) 0x72)
      (write-word char (+ fname 2) 0x76)
      (write-word char (+ fname 3) 0x0)
      ;; (puts fname)
      (let ((fd (upc-channel-open-network fname)))
        (upc-ocaml-add-socket fd)
        fd)))

(defun socketpair (domain type protocol socket-vector)
  (declare (external "socketpair"))
  (let ((fd (open-socket-fd)))
    (write-word int32_t socket-vector fd)
    (write-word int32_t (+ socket-vector (sizeof int32_t)) fd)
    0))

(defun upc-socket (domain tp protocol)
  (declare (external "socket"))
  (upc-ocaml-debug 0xfeebc0de)
  (open-socket-fd))


(defun upc-accept-internal (sock addr addrlen)
  (let ((af-inet 2)
        (no-test-cases (upc-ocaml-network-test-cases)))
    ;; Write af-inet into the sock-addr
    (write-word int addr af-inet)
    (write-word int (+ addr 4) 0x100007f)
    (write-word ptr_t addrlen 16)
    (if (= *network-test-case* no-test-cases)
      -1
      (let ((fname (malloc 16)))
      ;;(write-word ptr_t fname 0x3e74656e3c) ;; <net>
        (write-word char fname 0x6e)
        (write-word char (+ fname 1) 0x65)
        (write-word char (+ fname 2) 0x74)
        (upc-itoa (+ fname 3) *network-test-case*)
        ;;(write-word char (+ fname 3) 0x0)
        ;; (puts fname)
        (incr *network-test-case*)
        (let ((fd (upc-channel-open-network fname)))
          (upc-ocaml-network-fd sock fd)
          fd)))))

(defun upc-accept (sock addr addrlen)
  (declare (external "accept"))
  (upc-accept-internal sock addr addrlen))

(defun upc-accept4 (sock addr addrlen flags)
   (declare (external "accept4"))
   (upc-accept-internal sock addr addrlen))

(defun upc-setsockopt (fd level opt optval len)
  (declare (external "setsockopt"))
  0)

(defun upc-getpeername (sockfd sockaddr socklen)
  (declare (external "getpeername"))
  (write-word short sockaddr 2)
  (write-word int (+ sockaddr 4) 0x100007f)
  (write-word ptr_t socklen 16)
  0)

(defun upc-getsockname (sockfd sockaddr socklen)
  (declare (external "getsockname"))
  (write-word short sockaddr 2)
  (write-word ptr_t socklen 16)
  0)

(defun upc-listen (fd backlog)
  (declare (external "listen"))
  0)

(defun getaddrinfo (node service hints res)
  (declare (external "getaddrinfo"))
  (let ((addrinfo-size 48)
        (sockaddr-size 16)
        (addrinfo (malloc addrinfo-size))
        (sockaddr (malloc sockaddr-size)))
      (write-word ptr_t res addrinfo)
      (write-word int (+ addrinfo 4) *af-inet*)
      (write-word ptr_t (+ addrinfo 40) 0)
      (write-word ptr_t (+ addrinfo 24) sockaddr)
      (write-word ptr_t (+ addrinfo 16) 16)
      (write-word int sockaddr *af-inet*)
      (write-word int (+ sockaddr 4) 0x0a02a8c0))
  0)
