os: linux
dist: xenial
language: generic
sudo: required
services:
 - docker

script:
 - docker build --target build -f docker/Dockerfile -t sysflowtelemetry/uids:latest .
 - docker build -f docker/Dockerfile.util -t sysflowtelemetry/uids-util:latest .
 - docker run -v $PWD/tests/:/tests/ sysflowtelemetry/uids:latest /tests/fork _start "/fork/fork,/bin/bash,/bin/sh" /usr/bin/bash /fork/fork.sh promiscuous "%00000000"
 - docker run -v $PWD/tests/:/tests/ sysflowtelemetry/uids:latest /tests/echo _start "/echo/echo,/echo/echo.conf" /usr/bin/bash /echo/echo.sh promiscuous "%00000000" --primus-lisp-channel-redirect="/echo/echo.conf:/uIDS/tests/conf/echo.conf"
 - docker run -v $PWD/tests/:/tests/ sysflowtelemetry/uids:latest /tests/apr _start "/apr" /bin/bash /apr.sh greedy "%00000000"
 - docker run -v $PWD/tests/:/tests/ sysflowtelemetry/uids:latest /tests/CADET_00001 _start "/cgc/CADET_00001" /bin/bash /cgc/cadet.sh greedy "%00000f29" --primus-lisp-channel-redirect="<stdin>:/uIDS/tests/input/CADET_00001"

branches:
  only:
  - master

notifications:
  email: true
