os: linux
dist: xenial
language: generic
sudo: required
services:
 - docker

script:
 - docker build -t sysflowtelemetry/uids:latest .
 - docker run -v $PWD/uIDS/artifacts/:/artifacts sysflowtelemetry/uids:latest /artifacts/fork/fork-argv _start

branches:
  only:
  - master

notifications:
  email: true
