os: linux
dist: xenial
language: generic
sudo: required
services:
 - docker

script:
 - docker build -f docker/Dockerfile -t sysflowtelemetry/uids:latest .
 - docker build -f docker/Dockerfile.util -t sysflowtelemetry/uids-util:latest .
 - ./bin/setup-experiments
 - ./bin/util unpack -image fork
 - ./bin/util mount-layers -image fork
 - docker run -v $PWD/experiments/redhat/:/experiments/redhat/ sysflowtelemetry/uids:latest /experiments/redhat/fork/3/uIDS/fork _start "fork,/bin/bash,/bin/sh"

branches:
  only:
  - master

notifications:
  email: true
