import numpy as np
import matplotlib.pyplot as plt

N = 4
BOTH = (20, 35, 30, 35)
BAP = (10, 5, 10, 5)
LLVM = (25, 32, 34, 20)

ind = np.arange(N) # the x locations for the groups
width = 0.35       # the width of the bars: can also be len(x) sequence

p1 = plt.bar(ind, BOTH, width)
p2 = plt.bar(ind, BAP, width,
                  bottom=BOTH)

plt.ylabel('Count')
plt.xlabel('Nodes (Functions) and Edges (Function Calls) Detected by a Tool')
plt.title('Evaluating Call Graphs Generated by LLVM and BAP')
plt.xticks(ind, ('echo', 'nginx', 'redis', 'postgres'))
plt.yticks(np.arange(0, 81, 10))
plt.legend((p1[0], p2[0]), ('Both', 'BAP'))

plt.show()
