(in-package posix)

(defun uids-getuser-struct (name)
  (let ((len (* (sizeof ptr_t) 7))
        (user-offset (sizeof ptr_t))
        (group-offset (* (sizeof ptr_t) 2))
        (dir-offset 32)
        (m (malloc len))
        (homedir (malloc 10)))
    (write-word char homedir 0x2F)
    (write-word char (+ homedir 1) 0x68)
    (write-word char (+ homedir 2) 0x00)
    (write-word ptr_t (cast ptr_t (+ m user-offset)) 33)
    (write-word ptr_t (cast ptr_t (+ m group-offset)) 33)
    (write-word ptr_t (cast ptr_t (+ m dir-offset)) homedir)
    m))
